# @file example/lpss.conf

```ini
[lpss]
id=550e8400-e29b-41d4-a716-446655440000
version=1

[arch]
type=root
locator=partlabel:root.a
linux=/boot/vmlinuz-linux
initrd=/boot/initramfs-linux.img
options=quiet splash

[opensuse]
type=root
locator=partlabel:root.b
linux=/boot/vmlinuz
initrd=/boot/initrd
options=splash=silent